version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
